###запрос на вход получаем 3 куки
GET http://127.0.0.1:8080/auth/user-password

###запрос доступ, если есть access токен, то доступ предоставлен
GET http://127.0.0.1:8080/

###запрос обновление access токена, если действительны fingerprint и refresh token
GET http://127.0.0.1:8080/auth/refresh